### PR TITLE
Add greatworks && pldg pages for sp24

### PR DESCRIPTION
**Pull request by yy665**
Also may I have write access to the repo since I might be editing schedules quite often?

Thank you!

-Yulun

### CODE REVIEW

**Comment by od0x0** [comment]
Sorry, didn't mean to close it. I don't know who has the admin permissions needed to add people.

**Comment by yy665** [comment]
> Sorry, didn't mean to close it. I don't know who has the admin permissions needed to add people.

No problem! I will ask Adrian tomorrow, maybe he knows!

**Comment by rachitnigam** [comment]
Hey @od0x0! I've made you admin and I've given @yy665 write access!

**Comment by yy665** [comment]
> Hey @od0x0! I've made you admin and I've given @yy665 write access!

Thank you!!

**Pull request merged**
