### PR TITLE
Update news.md

### PR DESCRIPTION
**Pull request by dz333**
Add PDL PLDI news

@rachitnigam  (I would tag Oliver but I don't know his github handle)

### CODE REVIEW

**Comment by jnfoster** [comment]
Yay! Should we add the other PLDG papers, and also somehow indicate that the acceptances are conditional?

**Comment by dz333** [comment]
Agreed! I'll update the template to allow for a "conditionally accepted flag".
If someone sends me (DM on slack is fine) all of the papers that were conditionally accepted (authors + titles) then I can add them to this PR

**Comment by rachitnigam** [comment]
Thanks Drew! I've asked Oliver to tag himself in the PR. I'm at ASPLOS so might be unresponsive for long periods of time. I'll give you write access to the repo.

**Comment by Oddity0x0** [comment]
@Oddity0x0 is my (Oliver's) handle

**Comment by rachitnigam** [comment]
All right, Oliver you should have maintain access once you accept the invite!

**Pull request merged**
